# Generated by Django 2.0.5 on 2018-10-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_orm', '0002_auto_20181012_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
