# Generated by Django 2.0.5 on 2018-10-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('thumbnial', models.FileField(upload_to='files')),
            ],
        ),
    ]
