# Generated by Django 2.0.5 on 2018-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_demo', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnial',
            field=models.FileField(upload_to=''),
        ),
    ]
