# Generated by Django 2.0.5 on 2018-10-21 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_demo', '0004_auto_20181021_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnial',
            field=models.FileField(upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['txt'], message='必须为txt格式文件...')]),
        ),
    ]
